### ISSUE TITLE
Dargon.RADS Crash when facing multiple localized projects

### ISSUE THREAD

**Issue by miyu** [the-dargon-project/Dargon.RADS#1]
When facing 

```
lol_air_client              lol_air_client_config_na  lol_game_client_en_us
lol_air_client_config_eune  lol_game_client           lol_launcher
lol_air_client_config_euw   lol_game_client_en_gb     lol_patcher
```

Things explode with

```
System.ArgumentException was unhandled
  HResult=-2147024809
  Message=An item with the same key has already been added.
  Source=mscorlib
  StackTrace:
       at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
       at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
       at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
       at Dargon.RADS.RiotSolutionLoader.Load(String radsPath, Nullable`1 projectTypeLimit) in V:\my-repositories\dargon-root\dependencies\Dargon.RADS\RiotSolutionLoader.cs:line 23
       at dargon_asset_dumper.LoadSolutionCommand.Eval(String args) in V:\my-repositories\dargon-root\dargon\dargon-asset-dumper\Program.cs:line 212
       at Dargon.Nest.DispatcherCommand.Eval(String args) in V:\my-repositories\dargon-root\dependencies\Dargon.Repl\DispatcherCommand.cs:line 40
       at dargon_asset_dumper.Program.Main(String[] args) in V:\my-repositories\dargon-root\dargon\dargon-asset-dumper\Program.cs:line 30
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

Not sure what the best way to handle multiple shards is. We essentially don't care about the configs, so a simple fix would be to ignore them or use the last or first one found.

**Comment by RichieSams** [comment]
The localization folders store the localization strings, though. Which would be useful to modify for a mod.

**Comment by miyu** [comment]
Hmm true. Well,  perhaps in the future we should support picking a default region and installation directory. Then can detect localization at runtime later.

**Comment by miyu** [comment]
And for now perhaps default to en-us?
